import type { Metadata } from "next";
import "./globals.css";

import Navbar from "./components/GlobalComponents/Navbar";

import { Cormorant_Garamond, Inter } from "next/font/google";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  weight:["300","400","500","600","700"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight:["300","400","500","600","700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cormorant.variable} ${inter.variable}`}>
      <body
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
